# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 11
  - name: Projects
    url: '#projects'
    weight: 12
  - name: Talks
    url: '#talks'
    weight: 13
  - name: Publications
    url: '#publications'
    weight: 14
  - name: Other
    url: /other/
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 120

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.

  - name: Resumé/CV
    identifier: tags
    weight: 30
  - name: Resumé
    parent: tags
    url: uploads/resume.pdf
    weight: 20
  - name: Curriculum Vitae
    parent: tags
    url: uploads/CV_Benjamin_Meyer_August_2022.pdf
    weight: 40
  - name: PhD Interest Letter
    parent: tags
    url: uploads/letter_of_interest_meyer.pdf
    weight: 60

# not sure what to replace 'tags' with
