---
title: Climate Change and Juvenile Salmon Habitat in the Kenai River Watershed
author: Benjamin Meyer
date: '2022-03-06'
slug: climate-change-in-the-kenai-river-watershed
categories:
  - Salmon Habitat
tags:
  - Academic
  - Kenai
subtitle: ''
summary: ''
authors: []
lastmod: '2022-03-06T09:20:54-09:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

As the climate warms in Alaska, most stream temperatures will also warm. Warmer waters affect how juvenile salmon grow and live, but not all changes are made equal. Will wild salmon be able to handle the kinds of sweeping environmental changes that are coming in the next century?

My M.S. thesis at University of Alaska Fairbanks focused on juvenile salmon growth and diet in the Kenai River watershed in the context of climate change. We found that juvenile Chinook and Coho salmon in warmer, low-elevation streams may see decreased peak summer growth rates as air temperatures increase, whereas juvenile salmon in cooler, higher elevation streams may see a smaller magnitude of change.

A manuscript based on the first chapter of my thesis is currently in review; until then [you can access my thesis here.](https://www.benjamin-meyer.net/publications/meyer_2020_ms_thesis/)

test
