---
title: Wild Salmon Twitter Bot
author: Benjamin Meyer
date: '2022-03-06'
slug: wild-salmon-twitter-bot
categories:
  - Science Outreach
tags:
  - Salmon Habitat
subtitle: ''
summary: ''
authors: []
lastmod: '2022-03-06T09:41:42-09:00'
featured: no
image:
  caption: 'Art by Alex Testere'
  focal_point: ''
  preview_only: no
projects: []
---

In spring 2017 I found myself distracted one afternoon by all the news about bots on social media and their reported ability to influence political outcomes. There appeared to not yet be such a bot promoting all that wild salmon give to our world, so I made one. 

As of March 2022 the Twitter account `@wildsalmonbot` has tweeted 3,642 silly, non-sensical, and/or profound mad-libs style statements about wild salmon. The most popular tweet so far was on December 21, 2021:

*"Wild salmon are splish-splashin' party animals that will outlast us. #wildsalmon."*

I'm not how or why that tweet caught such traction, but it was flattering to know that my creation had an audience.

You can follow Wild Salmon Bot on Twitter here: <https://twitter.com/wildsalmonbot>

You can learn more about how I created the Twitter bot and how to make your own from [Prof. Zach Whalen's website](https://www.zachwhalen.net/posts/how-to-make-a-twitter-bot-with-google-spreadsheets-version-04/).
