---
title: On Being "The Balloon Guy"
author: Benjamin Meyer
date: '2016-10-14'
slug: business-is-blowing-up-for-uaf-s-balloon-guy
categories:
  - Science Outreach
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2022-02-25T06:45:18-09:00'
featured: no
image:
  caption: ' Photo Credit JR Ancheta'
  focal_point: ''
  preview_only: no
projects: []
---

From 2014 to 2020 I worked as my alter ego, [Ben The Balloon Guy](https://www.bentheballoonguy.com/), creating balloon art at over 150 events around Alaska. I've worked at six year olds' birthday parties to sixty year olds' retirement parties and everything in between.

[Link - October 16, 2016 - Business is Blowing Up for UAF's "Balloon Guy"](https://news.uaf.edu/business-is-blowing-up-for-uafs-balloon-guy/)

As The Balloon Guy I've been called upon to entertain mourning families, to distract infants while they're getting their vaccination shots, to teach science to classrooms, to make silly hats for the crowd just before afternoon nap time at a retirement center, to cheer up bored bureaucrats at a Monday morning meeting. It's an aspect of my life that's brought me to corners of the community that I never would have known existed and expanded my comfort zone beyond what I ever would have thought possible.

Being a balloon artist is like having a superpower: the ability to instantly produce an object of any shape or color that the imagination can create. Magically, I can have you wearing a jet pack, or butterfly wings, or a riding a motorcycle. You can have a pet shark on a leash. You can ride a unicorn. The instant smile effect worked just as well for energetic kindergartners as it did for stressed out parents or gruff grandpas.

As my side-hustle progressed it became more and more profitable, and I received offers for higher profile gigs. I had avoided the dreaded pigeonhole of being thought of purely kids entertainment, I was getting opportunities to work with professional artists and corporate clients. My artists' star was rising, my place in the community was respected.

Yet there were lingering doubts. I found myself in a rabbit hole of Youtube videos watching tropical rain forest being cleared to plant rubber plantations. I dreaded the harried parent who had waited in line forty five minutes with their child to receive a sword that would instantly pop as soon as they walked off. One time I was quickly escorted by a nurse out of a hospital wing where I'd gone to deliver a balloon bouquet, incognizant of the rules and concerns about latex allergies in medical facilities. Another day I found the popped remains of one of my creations tangled in a willow bush along the Chena River. It turned out that the instant-magic of my chosen medium had a lingering half-life beyond it's creation.

The pandemic hit in spring 2020, and the calls stopped coming. I was ready to take a break. I finally wrapped up my graduate thesis. I bought and old bus and began working to convert it to an RV. I took my dogs on more walks. It was nice to have some other creative outlets of my life back, and it still is today.

The many other balloon artists I've known and worked with have been some of the most interesting and odd folks I've ever come to know. I'll count myself as an emeritus among them. I still have about 10,000 balloons packed away in my garage and still break them out for the occasional special event.

The thing about balloons that they're ephemeral, they're temporary, they're disposable. You can use them to create magic for a moment, and that moment can last forever. But everything it took to produce that magic is not ephemeral. I don't believe that waste from balloons, or even similarly maligned ephemeral objects like...gasp...disposable straws...are the most concerning of environmental woes in our world. The thing about balloon art that no longer inspires me is this: when I'm on as the balloon guy, I'm setting an example of how to have fun, how to be entertaining, how to bring joy, and the example I'm setting is to have a practiced specialist hand out a shiny object that will become trash by the next morning.

I'm interested to have you tell me why I'm wrong, I miss certain parts of being Ben The Balloon Guy. I feel like he's still there but possibly searching for another medium to focus on. For now, convince me that you have a special event, and that my creations won't end up accidentally adrift choking a seagull, and I'll consider donning my alter ego again.
