---
# Documentation: https://wowchemy.com/docs/managing-content/

title: "How do wildfires affect juvenile salmon growth and diet?"
subtitle: ""
summary: ""
authors: []
tags: [Salmon Habitat, Alaska EPSCoR]
categories: []
date: 2021-11-22T07:23:21-09:00
lastmod: 2021-11-22T07:23:21-09:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "Photo Credit Seth Adams"
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
personal: []
---

Long after the smoke and flames are gone, wildfires continue to transform their ecosystems. I say wildfires have "their ecosystems," because they are truly the most prominent force shaping the boreal landscape. Wildfires belong. It's inconvenient for us they can also be destructive to our infrastructure, but wildfires will continue to do their business long after the last human has fled to Mars.

Wildfires affect more than just trees and homes. The loose char of the forest floor is much more easily washed away in the rain, where it ends up in rivers and lakes and affects water quality. As to what this means for juvenile salmon, how they eat and how they grow, remains a question for researchers. In the long term (5-20 year time span) there are good arguments that wildfires can enhance productivity of juvenile salmon rearing environments, with enhanced inputs of large woody debris and nutrients. In the short term, changes to turbidity have the potential to affect juvenile Chinook salmon feeding conditions.

In summer 2020 I had the privilege to work with some of my collaborators at University of Alaska Fairbanks to tackle this question. Dr. Erik Schoen developed a project to expand on an existing project with Dr. Jason Neuswanger. We used a variety of innovative approaches to investigate what juvenile Chinook salmon prey upon, how fast they grow, and what sort of water conditions they lived in. We deployed tools from drones to drift nets and everything in between to develop a unique data set.

Analysis and writing for this project is still underway. For now, you can check out some slides I presented at two meetings: the 2020 Mat-Su Salmon Symposium and the 2021 conference for the Alaska Chapter of the American Fisheries Society.

-   Article: [UAF researchers evaluate wildfire impact using unmanned aircraft (January 22,2021)](https://news.uaf.edu/researchers-evaluate-wildfire-impacts-using-unmanned-aircraft/)

-   [Link: Presentation Slides.](https://drive.google.com/drive/folders/1jkPaXeAzv4MS75AB1FIiUFKuNsCFOg_6?usp=sharing) (At this link to Google Drive, you'll find my presentation as well as two brief slides presented by Dr. Erik Schoen at the 2021 Alaska EPSCoR All-Hands meeting. All results shown are preliminary.)

-   [Link to Project Map](https://www.arcgis.com/apps/mapviewer/index.html?webmap=0bce982e438646e281cb9c6628bff021)
