---
title: Alaska's Missing Salmon Streams
author: Benjamin Meyer
date: '2022-08-23'
slug: alaskas-missing-salmon-streams
categories:
  - Salmon Habitat
tags:
  - Kenai Watershed Forum
  - Kenai
subtitle: ''
summary: ''
authors: []
lastmod: '2022-08-23T07:48:22-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
projects: []
---


topics

- matter et al 2018
- terrainworks storymap
 - kwf maping efforts
 - new fish map app
 - ballot measure 1 presumption of anadromy; how to verify absence of occupancy
 - TU collab
 
 
I am still surprised by some of the places where I find juvenile salmon. While adults leaping up waterfalls in to the jaws of grizzlies may be the star of the show, just as with any good production there is a vast crew of support staff and detailed logistics behind any wild salmons' story.

I found one such unsuspecting place last week in a powerline corridor just outside of Soldotna. A small tributary of the Moose River trickled down from wetlands through the Kenai National Wildlife Refuge. The map suggested there was no reason it wouldn't be populated by juvenile Silvers and Dolly Varden, but it was not yet included in the inventory of Alaska's known salmon streams, the Anadromous Waters Catalog...



intro of small crevices

Alaska has approximately 20,000 miles of documented 
 




