---
title: Giant Cabbage Limerick Contest
author: Benjamin Meyer
date: '2022-08-03'
slug: giant-cabbage-limerick-contest
categories:
  - Other
tags:
  - Poetry
subtitle: ''
summary: ''
authors: []
lastmod: '2022-08-03T07:49:20-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Each fall the Alaska State Fair hosts an annual Giant Cabbage Weigh-Off, where gardeners from around the state compete to see whose cabbage outweighs the competition. Either myself or someone in my family has entered a cabbage for most of the last two decades. We've never quite approached Scott Robb's 138 lb record monstrosity, but we've always done respectably.

Since 2019 I've been the organizer of the Giant Cabbage Weigh-Off Limerick Contest. Why a cabbage limerick contest? The origins are murky. Earlier years of the weigh-off had corporate sponsorship from Kraft Foods, which also sponsored a few side-contests including a Cabbage Limerick Contest. Some promoter likely had an affinity for the Irish poetic form of limericks, and thought cabbages went along nicely with them.

When Kraft dropped its sponsorship a dozen years ago, the limerick contest dropped off too. My parents, ever the state-fair enthusiasts, decided to take up the reins of the limerick contest (i.e. thought it would be a good idea if I organized it). The Meyer family has sponsored the limerick contest with cash prizes since 2019. I am the organizer of the contest, receiving all entries and recruiting judges.

We receive entries from all over the world starting in January! Some limericks are funny, some nostalgic, some gross; all of them are fun.

I'm in the process of assembling a highlights from this contest in to a booklet or website, for now you can check out the 2021 contest winners here:

[2021 Giant Cabbage Limerick Winners](https://drive.google.com/file/d/1M3_GiiT-iczf0_5JbHgmzDv7ZtW3vymi/view?usp=sharing)

You can enter your own giant cabbage limerick anytime by going to the Alaska State Fair website below:

<https://www.alaskastatefair.org/site/events/cabbage-limerick-contest/>

Happy gardening! If you are interested in being involved, I'm always looking for help. Be in touch!
